spring.application.name=backend

spring.data.mongodb.uri=mongodb://localhost:27017/gharkakhana
spring.data.mongodb.auto-index-creation=true

jwt.secret=veryLongSecretKeyThatShouldBeAtLeast64BytesLongForSecurityPurposesInProduction
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.error.include-message=always
